#!/usr/bin/env python

import os
import shutil
import glob

import datetime

import numpy as np
import pandas as pd
import xarray as xr

# Generate Output Directory
output_dir  = os.path.join('output','climo')
if os.path.exists(output_dir):
    shutil.rmtree(output_dir)
os.makedirs(output_dir)

# Find all available data files.
data_dir    = 'mstid_index'
pattern     = '*.nc'
data_fls    = glob.glob(os.path.join(data_dir,pattern))
data_fls.sort()

# Identify unique seasons available
seasons = []
for fl in data_fls:
    spl     = os.path.basename(fl).split('_')
    season  = '{!s}_{!s}'.format(spl[1],spl[2])
    seasons.append(season)
seasons = list(set(seasons))
seasons.sort()

radars          = []
# 'High Latitude Radars'
radars.append('pgr')
radars.append('sas')
radars.append('kap')
radars.append('gbr')
# 'Mid Latitude Radars'
radars.append('cvw')
radars.append('cve')
radars.append('fhw')
radars.append('fhe')
radars.append('bks')
radars.append('wal')

param = 'meanSubIntSpect_by_rtiCnt'

for season in seasons:

    # Load all data from a season into a single xarray dataset.
    ds      = []
    attrs   = []
    for radar in radars:
        fl  = os.path.join(data_dir,'sdMSTIDindex_{!s}_{!s}.nc'.format(season,radar))
        dsr = xr.open_dataset(fl)
        ds.append(dsr)
        attrs.append(dsr.attrs)
    dss = xr.concat(ds,dim='index')

    # Convert parameter of interest to a datafame.
    df      = dss[param].to_dataframe()
    dfrs    = []
    for radar in radars:
        tf      = df['radar'] == radar
        dft     = df[tf]
        dates   = dft.index
        vals    = dft[param]
        dfr     = pd.DataFrame({radar:vals},dates)
        dfrs.append(dfr)

    df = pd.concat(dfrs)
    df.index.name   = 'datetime'
    csv_fname       = '{!s}_{!s}.csv'.format(season,param)
    csv_fpath       = os.path.join(output_dir,csv_fname)
    with open(csv_fpath,'w') as fl:
        hdr = []
        hdr.append('# SuperDARN MSTID Index Datafile')
        hdr.append('# Generated by Nathaniel Frissell, nathaniel.frissell@scranton.edu')
        hdr.append('#')
        hdr.append('# Parameter: {!s}'.format(param))
        hdr.append('#')
        for attr in attrs:
            hdr.append('# {!s}'.format(attr))
        hdr.append('#')

        fl.write('\n'.join(hdr))
        fl.write('\n')
        
#        cols = ['datetime_ut'] + list(df.keys())
#        fl.write(','.join(cols))
#        fl.write('\n')
    df.to_csv(csv_fpath,mode='a')

import ipdb; ipdb.set_trace()
