#!/usr/bin/env python3
import os
import shutil
import tqdm

import numpy as np
import pandas as pd
import matplotlib as mpl

import xarray as xr

import pymongo

def generate_radar_dict():
    rad_list = []
    rad_list.append(('bks', 39.6, -81.1))
    rad_list.append(('wal', 41.8, -72.2))
    rad_list.append(('fhe', 42.5, -95.0))
    rad_list.append(('fhw', 43.3, -102.7))
    rad_list.append(('cve', 46.4, -114.6))
    rad_list.append(('cvw', 47.9, -123.4))
    rad_list.append(('gbr', 58.4, -59.9))
    rad_list.append(('kap', 55.5, -85.0))
    rad_list.append(('sas', 56.1, -103.8))
    rad_list.append(('pgr', 58.0, -123.5))

#    rad_list.append(('sto', 63.86, -21.031))
#    rad_list.append(('pyk', 63.77, -20.54))
#    rad_list.append(('han', 62.32,  26.61))

    radar_dict = {}
    for radar,lat,lon in rad_list:
        tmp                 = {}
        tmp['lat']          = lat
        tmp['lon']          = lon
        radar_dict[radar]   = tmp

    return radar_dict

output_dir  = os.path.join('data','mstid_index')
mongo_port  = 27017
#db_name     = 'mstid'
db_name     = 'fitexfilter'
prefix      = 'guc'

radar_dict  = generate_radar_dict()

# Prepare output dictionary.
if os.path.exists(output_dir):
    shutil.rmtree(output_dir)

os.makedirs(output_dir)

mongo   = pymongo.MongoClient(port=mongo_port)
db      = mongo[db_name]
lists   = db.list_collection_names()


keys = []
#keys.append('_id')
#keys.append('date')
#keys.append('sDatetime')
#keys.append('fDatetime')
#keys.append('radar')
#keys.append('lat')
#keys.append('lon')
keys.append('slt')
keys.append('mlt')
#keys.append('gscat')
#keys.append('height_km')
keys.append('terminator_fraction')
keys.append('good_period')
keys.append('orig_rti_cnt')
keys.append('orig_rti_fraction')
keys.append('orig_rti_mean')
keys.append('orig_rti_median')
keys.append('orig_rti_possible')
keys.append('orig_rti_std')
keys.append('intSpect')
keys.append('meanSubIntSpect')
keys.append('intSpect_by_rtiCnt')
keys.append('meanSubIntSpect_by_rtiCnt')
keys.append('category_manu')

attr_keys = []
attr_keys.append('radar')
attr_keys.append('lat')
attr_keys.append('lon')
#attr_keys.append('gscat')
#attr_keys.append('height_km')

seasons = []
for lst in lists:
    if not lst.startswith(prefix):
        continue

    spl = lst.split('_')
    seasons.append('{!s}_{!s}'.format(spl[2],spl[3]))

#with open('reject_codes.txt','w') as fl:
#    fl.write('')

seasons = list(set(seasons))
for season in tqdm.tqdm(seasons,desc='Seasons',dynamic_ncols=True,position=0):
    for radar in tqdm.tqdm(radar_dict.keys(),desc='Radars',dynamic_ncols=True,position=1,leave=False):
        lst = '_'.join([prefix,radar,season])

        if lst not in lists:
            continue

        dates           = []
        data            = {x:[] for x in keys}
        data['reject_code'] = []

        crsr = db.get_collection(lst).find()
        for item in crsr:
            date        = item['sDatetime']
            dates.append(date)

            for key in keys:
                data[key].append(item.get(key))

            # Possible Reject Messages:
            # ['No RTI Fraction', 'No Data', 'High Terminator Fraction', 'Failed Quality Check', 'No Terminator Fraction', 'Low RTI Fraction']
            reject = item.get('reject_message')
            if reject is None:
                reject_code = 0 # Good period
            elif 'High Terminator Fraction' in reject:
                reject_code = 1 # Dawn/Dusk
            elif 'No Data' in reject:
                reject_code = 2 # No Data
            elif ('Failed Quality Check' in reject) or ('Low RTI Fraction' in reject):
                reject_code = 3 # Poor data quality
            else:
                reject_code = 4 # Other, including No RTI Fraction and No Terminator Fraction.
            data['reject_code'].append(reject_code)

#            txt = '{!s}: {!s} {!s} {!s}\n'.format(reject_code, radar, date, reject)
#            print(txt)
#            with open('reject_codes.txt','a') as fl:
#                fl.write(txt)

        
        df      = pd.DataFrame(data,index=dates)
        attrs   = {'season':season}
        for attr_key in attr_keys:
            attrs[attr_key] = item.get(attr_key)

        csv_path = os.path.join(output_dir,'sdMSTIDindex_{!s}_{!s}.csv'.format(season,radar))
        with open(csv_path,'w') as fl:
            hdr = []
            hdr.append('# SuperDARN MSTID Index')
            hdr.append('# Generated by Nathaniel Frissell, nathaniel.frissell@scranton.edu')
            hdr.append('#')
            for attr_key,attr in attrs.items():
                hdr.append('# {!s}: {!s}'.format(attr_key,attr))
            hdr.append('#')

            hdr.append('# reject_code Explanations:')
            hdr.append('#   0: Good Period (Not Rejected)')
            hdr.append('#   1: High Terminator Fraction (Dawn/Dusk in Observational Window')
            hdr.append('#   2: No Data')
            hdr.append('#   3: Poor Data Quality (including "Low RTI Fraction" and "Failed Quality Check")')
            hdr.append('#   4: Other (including "No RTI Fraction" and "No Terminator Fraction")')
            hdr.append('#')

            fl.write('\n'.join(hdr))
            fl.write('\n')
            
            cols = ['datetime_ut'] + list(df.keys())
            fl.write(','.join(cols))
            fl.write('\n')
        df.to_csv(csv_path,mode='a',header=False)

        dsr = df.to_xarray()
        dsr = dsr.assign_coords({'radar':radar})
        dsr.attrs = attrs
        nc_path = os.path.join(output_dir,'sdMSTIDindex_{!s}_{!s}.nc'.format(season,radar))
        dsr.to_netcdf(nc_path)

import ipdb; ipdb.set_trace()
